export const SPOTIFY_AUTH_SUCCESS = 'SPOTIFY_AUTH_SUCCESS';
export const SPOTIFY_AUTH_ERROR = 'SPOTIFY_AUTH_ERROR';

export const BATCH_SEARCH_START = 'BATCH_SEARCH_START';
export const BATCH_SEARCH_COMPLETE = 'BATCH_SEARCH_COMPLETE';
export const BATCH_SEARCH_ITEM_COMPLETE ='BATCH_SEARCH_ITEM_COMPLETE';
export const BATCH_SEARCH_ITEM_ERROR = 'BATCH_SEARCH_ITEM_ERROR';

export const TRACK_SAVE_START = 'TRACK_SAVE_START';
export const TRACK_SAVE_COMPLETE = 'TRACK_SAVE_COMPLETE';
export const TRACK_SAVE_ERROR = 'TRACK_SAVE_ERROR';